### ISSUE TITLE
Create grammar reference of ZS

### ISSUE THREAD

**Issue by CommanderTvis** [CraftTweaker/ZenScript#35]
I am thinking of creating IntelliJ IDEA plugin for ZenScript. Is there a grammar reference of the language to implement a custom parser of ZS?

**Comment by CommanderTvis** [comment]
I've reviewed the code of the parser in this repository, but there is no documentation of it, and I am afraid to create an invalid one.

**Comment by CommanderTvis** [comment]
Is this grammar actual?
https://github.com/CraftTweaker/ZenScriptIntelliJPlugin/blob/master/src/de/bloodworkxgaming/zenscript/plugin/zsLanguage/psi/ZenScript.bnf

**Comment by CommanderTvis** [comment]
@kindlich

**Comment by kindlich** [comment]
Blood wrote that a while back, so some stuff like zenClasses are still missing.
I can write you an actual BNF (only the bnf and the regex's for the tokens) when I get to it.

Just for reference, you are looking for the version we used in 1.12, correct?
1.14 and 1.15 use ZenCode (sometimes also called ZenScript 2) which looks a little different.
You can find a simple Bnf for ZenCode here
<https://gist.github.com/kindlich/2cd722d05915d165cdc607b343e08a92>

**Comment by CommanderTvis** [comment]
The best option is to implement 1.14 support first, 1.12 next, I think

**Comment by CommanderTvis** [comment]
Does ZenCode use this repo?

**Comment by kindlich** [comment]
Mostly this one, either from me or from Jared
<https://git.openzen.org/kindlich/ZenScript/src/branch/development>

The one from Jared is the one that CrT usually uses, but for the sake of the grammar they should be similar enough
<https://git.openzen.org/jared/ZenScript/src/branch/development>

**Comment by kindlich** [comment]
I can also send you a first impl of a Idea plugin that uses that grammar if you don't want to go through all the setup stuff, since I was working on that a while back (and just updated the grammar so a lot of stuff is still commented out as it wasn't adapted yet).

But if you want to take a look, I just pushed some changes to that branch here
<https://github.com/kindlich/ZenCodeIntelliJPlugin/tree/dev>

I probably won't be working on that too much in the forseeable future, so feel free to use that code 😜

**Comment by CommanderTvis** [comment]
Ok :)

**Comment by CommanderTvis** [comment]
It is a good stub

**Comment by CommanderTvis** [comment]
I wi
